import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthSession from "../components/AuthSession";
import Navbar from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import Head from "next/head"
import { Toaster } from 'react-hot-toast';
import StripeProvider from "@/components/payment/StripeProvider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    
      <body
      
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthSession>
        <Toaster position="top-right" reverseOrder={false} />
          <Navbar />
          <StripeProvider> {children}</StripeProvider>
          <Footer />
        </AuthSession>
      </body>
    </html>
  );
}
